name: Daily HallHop Outreach

on:
  schedule:
    - cron: "0 14 * * *"  # Runs at 9:00 AM CT (14:00 UTC)
  workflow_dispatch:      # Allows manual trigger

jobs:
  send_emails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run outreach script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python outreach.py
